// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `comstatusice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <comstatusice.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __interfaceICE__ComStatusICE__sportsCMDStatus_name = "sportsCMDStatus";

}
::IceProxy::Ice::Object* ::IceProxy::interfaceICE::upCast(::IceProxy::interfaceICE::ComStatusICE* p) { return p; }

void
::IceProxy::interfaceICE::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::interfaceICE::ComStatusICE>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::interfaceICE::ComStatusICE;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::interfaceICE::ComStatusICE::sportsCMDStatus(::Ice::Int __p_com, ::Ice::Int __p_status, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __interfaceICE__ComStatusICE__sportsCMDStatus_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_com);
        __os->write(__p_status);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::interfaceICE::ComStatusICE::begin_sportsCMDStatus(::Ice::Int __p_com, ::Ice::Int __p_status, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __interfaceICE__ComStatusICE__sportsCMDStatus_name, __del, __cookie);
    try
    {
        __result->prepare(__interfaceICE__ComStatusICE__sportsCMDStatus_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_com);
        __os->write(__p_status);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::interfaceICE::ComStatusICE::end_sportsCMDStatus(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __interfaceICE__ComStatusICE__sportsCMDStatus_name);
}

const ::std::string&
IceProxy::interfaceICE::ComStatusICE::ice_staticId()
{
    return ::interfaceICE::ComStatusICE::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::interfaceICE::ComStatusICE::__newInstance() const
{
    return new ComStatusICE;
}

::Ice::Object* interfaceICE::upCast(::interfaceICE::ComStatusICE* p) { return p; }

namespace
{
const ::std::string __interfaceICE__ComStatusICE_ids[2] =
{
    "::Ice::Object",
    "::interfaceICE::ComStatusICE"
};

}

bool
interfaceICE::ComStatusICE::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__interfaceICE__ComStatusICE_ids, __interfaceICE__ComStatusICE_ids + 2, _s);
}

::std::vector< ::std::string>
interfaceICE::ComStatusICE::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__interfaceICE__ComStatusICE_ids[0], &__interfaceICE__ComStatusICE_ids[2]);
}

const ::std::string&
interfaceICE::ComStatusICE::ice_id(const ::Ice::Current&) const
{
    return __interfaceICE__ComStatusICE_ids[1];
}

const ::std::string&
interfaceICE::ComStatusICE::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::interfaceICE::ComStatusICE";
    return typeId;
#else
    return __interfaceICE__ComStatusICE_ids[1];
#endif
}

::Ice::DispatchStatus
interfaceICE::ComStatusICE::___sportsCMDStatus(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int __p_com;
    ::Ice::Int __p_status;
    __is->read(__p_com);
    __is->read(__p_status);
    __inS.endReadParams();
    sportsCMDStatus(__p_com, __p_status, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __interfaceICE__ComStatusICE_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sportsCMDStatus"
};

}

::Ice::DispatchStatus
interfaceICE::ComStatusICE::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__interfaceICE__ComStatusICE_all, __interfaceICE__ComStatusICE_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __interfaceICE__ComStatusICE_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___sportsCMDStatus(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
interfaceICE::ComStatusICE::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
interfaceICE::ComStatusICE::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
interfaceICE::__patch(ComStatusICEPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::interfaceICE::ComStatusICEPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::interfaceICE::ComStatusICE::ice_staticId(), v);
    }
}
